/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScreenerImport } from './routes/screener'
import { Route as StocksSymbolImport } from './routes/stocks/$symbol'

// Create Virtual Routes

const MarketsLazyImport = createFileRoute('/markets')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MarketsLazyRoute = MarketsLazyImport.update({
  path: '/markets',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/markets.lazy').then((d) => d.Route))

const ScreenerRoute = ScreenerImport.update({
  path: '/screener',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const StocksSymbolRoute = StocksSymbolImport.update({
  path: '/stocks/$symbol',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerImport
      parentRoute: typeof rootRoute
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsLazyImport
      parentRoute: typeof rootRoute
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/screener': typeof ScreenerRoute
  '/markets': typeof MarketsLazyRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/screener': typeof ScreenerRoute
  '/markets': typeof MarketsLazyRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/screener': typeof ScreenerRoute
  '/markets': typeof MarketsLazyRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/screener' | '/markets' | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/screener' | '/markets' | '/stocks/$symbol'
  id: '__root__' | '/' | '/screener' | '/markets' | '/stocks/$symbol'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ScreenerRoute: typeof ScreenerRoute
  MarketsLazyRoute: typeof MarketsLazyRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ScreenerRoute: ScreenerRoute,
  MarketsLazyRoute: MarketsLazyRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/screener",
        "/markets",
        "/stocks/$symbol"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/screener": {
      "filePath": "screener.tsx"
    },
    "/markets": {
      "filePath": "markets.lazy.tsx"
    },
    "/stocks/$symbol": {
      "filePath": "stocks/$symbol.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
